version: '3'
services:
  site3:
    image: httpd
    container_name: site3
    restart: always
    environment: 
      - VIRTUAL_HOST=site3.com      
    volumes:
      - ./public/:/usr/local/apache2/htdocs/
    ports:
      - 83:80
    expose:
      - 83

networks:
  default:
    external:
      name: nginx-proxy