version: '3'
services:
  site2:
    image: httpd
    container_name: site2
    restart: always
    environment: 
      - VIRTUAL_HOST=site2.com
    volumes:
      - ./public/:/usr/local/apache2/htdocs/
    ports:
      - 82:80
    expose:
      - 82

networks:
  default:
    external:
      name: nginx-proxy